//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String tab_space = "    ";
   public int count;
   public int next_temp() {
      count++;
      return count;
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("MAIN");
      n.f1.accept(this, argu);
      System.out.println("END\n");
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      //n.f0.accept(this, argu);
      for (Enumeration<Node> e = n.f0.elements(); e.hasMoreElements();) {
         for (Enumeration<Node> e1 = ((NodeSequence)e.nextElement()).elements(); e1.hasMoreElements();) {
            String lbl = (String) e1.nextElement().accept(this, argu);
            if (lbl != null) {
               System.out.println(lbl);
            }
         }
      }
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      String lbl = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Integer val = (Integer) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      System.out.println(lbl + " [" + val + "]");
      n.f4.accept(this, (A) "hi");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println(tab_space+ "NOOP");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println(tab_space + "ERROR");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String exp = (String) n.f1.accept(this, argu);
      String lbl = (String) n.f2.accept(this, argu);
      System.out.println(tab_space + "CJUMP " + exp + " " + lbl);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String lbl = (String) n.f1.accept(this, argu);
      System.out.println(tab_space + "JUMP " + lbl);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String e1 = (String) n.f1.accept(this, argu);
      Integer val = (Integer) n.f2.accept(this, argu);
      String e2 = (String) n.f3.accept(this, argu);
      System.out.println(tab_space + "HSTORE " + e1 + " " + val + " " + e2);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String) n.f1.accept(this, argu);
      String e1 = (String) n.f2.accept(this, argu);
      Integer val = (Integer) n.f3.accept(this, argu);
      System.out.println(tab_space + "HLOAD " + t1 + " " + e1 + " " + val);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String) n.f1.accept(this, argu);
      String e1 = (String) n.f2.accept(this, argu);
      System.out.println(tab_space + "MOVE " + t1 + " " + e1);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String e1 = (String) n.f1.accept(this, argu);
      System.out.println(tab_space + "PRINT " + e1);
      return _ret;
   }

   /**
    * f0 -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      if (n.f0.which == 5) {
         Integer val = (Integer) _ret;
         int t1 = next_temp();
         System.out.println(tab_space + "MOVE TEMP " + t1 + " " + val);
         _ret = (R) ("TEMP " + t1);
      } else if (n.f0.which == 6) {
         String l1 = (String) _ret;
         int t1 = next_temp();
         System.out.println(tab_space + "MOVE TEMP " + t1 + " " + l1);
         _ret = (R) ("TEMP " + t1);
      }
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;

      boolean check = false;
      if (argu != null) check = true;
      argu = null;
      
      if (check) System.out.println("BEGIN");
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String exp = (String) n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      if (check) {
         System.out.println("RETURN");
         System.out.println(tab_space + exp);
         System.out.println("END\n");
      }
      _ret = (R) exp;
      return _ret;
   }

   public ArrayList<String> call_helper(NodeListOptional n) {
      ArrayList<String> expList = new ArrayList<>();
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         String exp = (String) e.nextElement().accept(this, null);
         expList.add(exp);
      }
      return expList;
   }
   /**
    * f0 -> "CALL"
    * f1 -> Exp()
    * f2 -> "("
    * f3 -> ( Exp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String e1 = (String) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      //n.f3.accept(this, argu);
      ArrayList<String> expList = call_helper(n.f3);
      n.f4.accept(this, argu);

      String res = "CALL " + e1 + " (";
      for (int i = 0; i < expList.size(); i++) {
         if (i == expList.size() - 1) res += expList.get(i);
         else res += expList.get(i) + " ";
      }
      res += ")";
      int t1 = next_temp();
      System.out.println(tab_space + "MOVE TEMP " + t1 + " " + res);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String e1 = (String) n.f1.accept(this, argu);
      int t1 = next_temp();
      System.out.println(tab_space + "MOVE TEMP " + t1 + " HALLOCATE " + e1);
      _ret = (R) ("TEMP " + t1);
      return _ret; 
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String) n.f0.accept(this, argu);
      String e1 = (String) n.f1.accept(this, argu);
      String e2 = (String) n.f2.accept(this, argu);
      int t1 = next_temp();
      if (n.f1.f0.which == 5) {
         int t2 = next_temp();
         System.out.println(tab_space + "MOVE TEMP " + t2 + " " + e1);
         e1 = "TEMP " + t2;
      }
      System.out.println(tab_space + "MOVE TEMP " + t1 + " " + op + " " + e1 + " " + e2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String exp = "";
      switch (n.f0.which) {
         case 0: exp = "LE"; break;
         case 1: exp = "NE"; break;
         case 2: exp = "PLUS"; break;
         case 3: exp = "MINUS"; break;
         case 4: exp = "TIMES"; break;
         case 5: exp = "DIV"; break;
         default: break;
      }
      _ret = (R) exp;
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer val = (Integer) n.f1.accept(this, argu);
      _ret = (R) ("TEMP " + val);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) (Integer)Integer.parseInt(n.f0.toString());
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) n.f0.toString();
      return _ret;
   }

}
