//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import helper.*;
/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */

public class FirstPass<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public HashMap<String, helper.UseDef> methodMap = new HashMap<>();
   public HashMap<String, HashMap<Integer, TreeSet<Integer>>> successorMap = new HashMap<>();
   public HashMap<String, Integer> method_sline_map = new HashMap<>();
   public HashMap<String, Integer> method_eline_map = new HashMap<>();
   public HashMap<String, Integer> method_max_arg_mapping = new HashMap<>();

   HashMap<String, Integer> label_line_count_map = new HashMap<>();
   HashMap<String, TreeSet<Integer>> curr_succ_map = new HashMap<>();
   HashMap<Integer, Integer> unmapped_succ = new HashMap<>();
   helper.UseDef current_map = new helper.UseDef();
   public int line_count = 1;
   int method_start_line;
   String current_method = "";

   void add_entry_to_succ_map(String method_name) {
      HashMap<Integer, TreeSet<Integer>> new_map = new HashMap<>();
      for (Map.Entry<String, TreeSet<Integer>> entry : curr_succ_map.entrySet()) {
         for (Integer val : entry.getValue()) {
            new_map.computeIfAbsent(val, k -> new TreeSet<>()).add(label_line_count_map.get(entry.getKey()));
         }
      }
      for (int i = method_start_line; i < line_count - 1; i++) {
         if (!unmapped_succ.containsKey(i)) {
            new_map.computeIfAbsent(i, k -> new TreeSet<>()).add(i + 1);
         }
      }
      successorMap.put(method_name, new_map);
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      method_start_line = line_count;
      method_sline_map.put("MAIN", method_start_line);
      current_method = "MAIN";
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      method_eline_map.put("MAIN", line_count);
      methodMap.put("MAIN", current_map);
      add_entry_to_succ_map("MAIN");
      current_map = new helper.UseDef();
      label_line_count_map = new HashMap<>();
      curr_succ_map = new HashMap<>();
      unmapped_succ = new HashMap<>();
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      for (Enumeration<Node> e = n.f0.elements(); e.hasMoreElements();) {
         for (Enumeration<Node> e1 = ((NodeSequence)e.nextElement()).elements(); e1.hasMoreElements();) {
            String lb = (String) e1.nextElement().accept(this, null);
            if (lb != null) {
               label_line_count_map.put(lb, line_count);
            }
         }
      }
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      String name = (String) n.f0.accept(this, argu);
      current_method = name;
      n.f1.accept(this, argu);
      Integer val = (Integer) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      method_start_line = line_count;
      method_sline_map.put(name, method_start_line);
      method_max_arg_mapping.put(name, 0);
      current_map.def_by_line.put(line_count, new TreeSet<>());
      for (int i = 0; i < val; i++) {
         TreeSet<Integer> temp1 = new TreeSet<>();
         temp1.add(line_count);
         current_map.def_at.put(i, temp1);
         current_map.def_by_line.get(line_count).add(i);
         
      }
      line_count++;
      n.f4.accept(this, argu);

      method_eline_map.put(name, line_count);
      methodMap.put(name, current_map);
      add_entry_to_succ_map(name);
      curr_succ_map = new HashMap<>();
      label_line_count_map = new HashMap<>();
      current_map = new helper.UseDef();
      unmapped_succ = new HashMap<>();
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      line_count++;
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer t1 = (Integer) n.f1.accept(this, argu);
      String lb = (String) n.f2.accept(this, argu);
      current_map.use_at.computeIfAbsent(t1, k -> new TreeSet<>())
                        .add(line_count);
      current_map.used_by_line.put(line_count, new TreeSet<>(List.of(t1)));
      curr_succ_map.computeIfAbsent(lb, k -> new TreeSet<>()).add(line_count);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String lb = (String) n.f1.accept(this, argu);
      curr_succ_map.computeIfAbsent(lb, k -> new TreeSet<>()).add(line_count);
      unmapped_succ.put(line_count, line_count + 1);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer t1 = (Integer) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Integer t2 = (Integer) n.f3.accept(this, argu);
      current_map.use_at.computeIfAbsent(t2, k -> new TreeSet<>())
                        .add(line_count);
      current_map.use_at.computeIfAbsent(t1, k -> new TreeSet<>())
                        .add(line_count);
      current_map.used_by_line.put(line_count, new TreeSet<>(List.of(t1, t2)));
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer t1 = (Integer) n.f1.accept(this, argu);
      Integer t2 = (Integer) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      current_map.use_at.computeIfAbsent(t2, k -> new TreeSet<>())
                        .add(line_count);
      current_map.def_at.computeIfAbsent(t1, k -> new TreeSet<>())
                        .add(line_count);
      current_map.used_by_line.put(line_count, new TreeSet<>(List.of(t2)));
      current_map.def_by_line.put(line_count, new TreeSet<>(List.of(t1)));

      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer t1 = (Integer) n.f1.accept(this, argu);
      current_map.def_at.computeIfAbsent(t1, k -> new TreeSet<>())
                        .add(line_count);
      current_map.def_by_line.put(line_count, new TreeSet<>(List.of(t1)));
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      line_count++;
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      for (Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
         Integer t = (Integer) e.nextElement().accept(this, argu);
         current_map.use_at.computeIfAbsent(t, k -> new TreeSet<>())
                           .add(line_count);
         current_map.used_by_line.computeIfAbsent(line_count, k -> new TreeSet<>())
                                 .add(t);
      }
      if (!method_max_arg_mapping.containsKey(current_method)) {
         method_max_arg_mapping.put(current_method, 0);
      }
      int val = method_max_arg_mapping.get(current_method);
      if (val < n.f3.size()) {
         method_max_arg_mapping.put(current_method, n.f3.size());
      }
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer t1 = (Integer) n.f1.accept(this, argu);
      current_map.use_at.computeIfAbsent(t1, k -> new TreeSet<>())
                           .add(line_count);
      current_map.used_by_line.computeIfAbsent(line_count, k -> new TreeSet<>())
                                 .add(t1);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      R val = n.f0.accept(this, argu);
      if (n.f0.which == 0) {
         Integer t = (Integer) val;
         current_map.use_at.computeIfAbsent(t, k -> new TreeSet<>())
                           .add(line_count);
         current_map.used_by_line.computeIfAbsent(line_count, k -> new TreeSet<>())
                                 .add(t);
      }
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      _ret = (R) (Integer.valueOf(n.f1.f0.toString()));
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) Integer.valueOf(n.f0.toString());
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) (n.f0.toString());
      return _ret;
   }

}
