//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class SecondPass<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
    public HashMap<String, Integer> method_max_arg_mapping;
    public HashMap<String, HashMap<Integer, String>> register_mapping;
    public HashMap<String, HashMap<Integer, Integer>> stack_mapping;
    int fresh_label = 0;
    String get_fresh_label() {
        fresh_label++;
        return "L_ved" + fresh_label;
    }
    String tab_space = "    ";
    HashMap<Integer, String> curr_reg_map;
    HashMap<Integer, Integer> curr_stack_map;
    HashMap<String, String> label_mapping = new HashMap<>();
    int curr_spilled_args = 0;

    public R visit(NodeList n, A argu) {
        R _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
        }
        return _ret;
    }

    public R visit(NodeListOptional n, A argu) {
        if ( n.present() ) {
            R _ret=null;
            int _count=0;
            for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
                e.nextElement().accept(this,argu);
                _count++;
            }
            return _ret;
        }
        else
            return null;
    }

    public R visit(NodeOptional n, A argu) {
        if ( n.present() )
            return n.node.accept(this,argu);
        else
            return null;
    }

    public R visit(NodeSequence n, A argu) {
        R _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
        }
        return _ret;
    }

    public R visit(NodeToken n, A argu) { return null; }

    //
    // User-generated visitor methods below
    //

    /**
        * f0 -> "MAIN"
        * f1 -> StmtList()
        * f2 -> "END"
        * f3 -> ( Procedure() )*
        * f4 -> <EOF>
        */
    public R visit(Goal n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        curr_reg_map = register_mapping.get("MAIN");
        curr_stack_map = stack_mapping.get("MAIN");
        curr_spilled_args = 0;
        System.out.println("MAIN [0] [" + (22 + curr_stack_map.size()) + "] [" + method_max_arg_mapping.get("MAIN") + "]");

        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        System.out.println("END");
        System.out.println("// " + (curr_stack_map.size() > 0 ? "SPILLED" : "NOTSPILLED") + "\n");
        label_mapping = new HashMap<>();

        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
        * f0 -> ( ( Label() )? Stmt() )*
        */
    public R visit(StmtList n, A argu) {
        R _ret=null;
        // n.f0.accept(this, argu);
        for (Enumeration<Node> e = n.f0.elements(); e.hasMoreElements();) {
            for (Enumeration<Node> e_ = ((NodeSequence)e.nextElement()).elements(); e_.hasMoreElements();) {
                String l1 = (String) e_.nextElement().accept(this, null);
                if (l1 != null) {
                    if (label_mapping.containsKey(l1)) {
                        System.out.println(label_mapping.get(l1));
                    } else {
                        String l2 = get_fresh_label();
                        System.out.println(l2);
                        label_mapping.put(l1, l2);
                    }
                }
            }
        }
        return _ret;
    }

    /**
        * f0 -> Label()
        * f1 -> "["
        * f2 -> IntegerLiteral()
        * f3 -> "]"
        * f4 -> StmtExp()
        */
    public R visit(Procedure n, A argu) {
        R _ret=null;
        String l1 = (String) n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        Integer args = (Integer) n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        curr_reg_map = register_mapping.get(l1);
        curr_spilled_args = Math.max(args - 4, 0);
        curr_stack_map = stack_mapping.get(l1);
        System.out.println(l1 + " [" + args +"] [" + (22 + curr_spilled_args + curr_stack_map.size()) + "] [" + method_max_arg_mapping.get(l1) + "]");
        

        for (int i = 0; i < 8; i++) {
            System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.size() + i) + " s" + i);
        }

        for (int i = 0; i < Math.min(4, args); i++) {
            if (!curr_reg_map.containsKey(i) && !curr_stack_map.containsKey(i)) continue;
            if (curr_reg_map.containsKey(i)) {
                System.out.println(tab_space + "MOVE " + curr_reg_map.get(i) + " a" + i);
            } else {
                System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(i)) + " a" + i);
            }
        }
        for (int i = 4; i < args; i++) {
            if (!curr_reg_map.containsKey(i) && !curr_stack_map.containsKey(i)) continue;
            if (curr_reg_map.containsKey(i)) {
                System.out.println(tab_space + "ALOAD " + curr_reg_map.get(i) + " SPILLEDARG " + (i - 4));
            } else {
                System.out.println(tab_space + "ALOAD v0 SPILLEDARG " + (i - 4));
                System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(i)) + " v0");
            }
        }

        n.f4.accept(this, argu);
        for (int i = 0; i < 8; i++) {
            System.out.println(tab_space + "ALOAD s" + i + " SPILLEDARG " + (curr_spilled_args + curr_stack_map.size() + i));
        }
        System.out.println("END");
        System.out.println("// " + (curr_stack_map.size() > 0 ? "SPILLED" : "NOTSPILLED") + "\n");
        label_mapping = new HashMap<>();

        return _ret;
    }

    /**
        * f0 -> NoOpStmt()
        *       | ErrorStmt()
        *       | CJumpStmt()
        *       | JumpStmt()
        *       | HStoreStmt()
        *       | HLoadStmt()
        *       | MoveStmt()
        *       | PrintStmt()
        */
    public R visit(Stmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
        * f0 -> "NOOP"
        */
    public R visit(NoOpStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        System.out.println(tab_space + "NOOP");
        return _ret;
    }

    /**
        * f0 -> "ERROR"
        */
    public R visit(ErrorStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        System.out.println(tab_space + "ERROR");
        return _ret;
    }

    /**
        * f0 -> "CJUMP"
        * f1 -> Temp()
        * f2 -> Label()
        */
    public R visit(CJumpStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        Integer t1 = (Integer) n.f1.accept(this, argu);
        String l1 = (String) n.f2.accept(this, argu);
        if (label_mapping.containsKey(l1)) {
            l1 = label_mapping.get(l1);
        } else {
            String l2 = get_fresh_label();
            label_mapping.put(l1, l2);
            l1 = l2;
        }
        if (curr_reg_map.containsKey(t1)) {
            System.out.println(tab_space + "CJUMP " + curr_reg_map.get(t1) + " " + l1);
        } else {
            System.out.println(tab_space + "ALOAD v0 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t1)));
            System.out.println(tab_space + "CJUMP v0 " + l1);
        }

        return _ret;
    }

    /**
        * f0 -> "JUMP"
        * f1 -> Label()
        */
    public R visit(JumpStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        String l1 = (String) n.f1.accept(this, argu);
        if (label_mapping.containsKey(l1)) {
            l1 = label_mapping.get(l1);
        } else {
            String l2 = get_fresh_label();
            label_mapping.put(l1, l2);
            l1 = l2;
        }
        System.out.println(tab_space + "JUMP " + l1);

        return _ret;
    }

    /**
        * f0 -> "HSTORE"
        * f1 -> Temp()
        * f2 -> IntegerLiteral()
        * f3 -> Temp()
        */
    public R visit(HStoreStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        Integer t1 = (Integer) n.f1.accept(this, argu);
        Integer val = (Integer) n.f2.accept(this, argu);
        Integer t2 = (Integer) n.f3.accept(this, argu);
        String t1_reg, t2_reg;

        if (curr_reg_map.containsKey(t1)) {
            t1_reg = curr_reg_map.get(t1);
        } else {
            System.out.println(tab_space + "ALOAD v0 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t1)));
            t1_reg = "v0";
        }

        if (curr_reg_map.containsKey(t2)) {
            t2_reg = curr_reg_map.get(t2);
        } else {
            System.out.println(tab_space + "ALOAD v1 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t2)));
            t2_reg = "v1";
        }

        System.out.println(tab_space + "HSTORE " + t1_reg + " " + val + " " + t2_reg);
        return _ret;
    }

    /**
        * f0 -> "HLOAD"
        * f1 -> Temp()
        * f2 -> Temp()
        * f3 -> IntegerLiteral()
        */
    public R visit(HLoadStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        Integer t1 = (Integer) n.f1.accept(this, argu);
        Integer t2 = (Integer) n.f2.accept(this, argu);
        Integer val = (Integer) n.f3.accept(this, argu);
        String t1_reg, t2_reg;

        if (!curr_reg_map.containsKey(t1) && !curr_stack_map.containsKey(t1)) return _ret;

        if (curr_reg_map.containsKey(t1)) {
            t1_reg = curr_reg_map.get(t1);
        } else {
            t1_reg = "v0";
        }

        if (curr_reg_map.containsKey(t2)) {
            t2_reg = curr_reg_map.get(t2);
        } else {
            System.out.println(tab_space + "ALOAD v1 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t2)));
            t2_reg = "v1";
        }

        System.out.println(tab_space + "HLOAD " + t1_reg + " " + t2_reg + " " + val);
        if (t1_reg == "v0") {
            System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t1)) + " v0");
        }
        return _ret;
    }

    /**
        * f0 -> "MOVE"
        * f1 -> Temp()
        * f2 -> Exp()
        */
    public R visit(MoveStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        Integer t1 = (Integer) n.f1.accept(this, argu);
        String exp = (String) n.f2.accept(this, argu);
        String t1_reg;

        if (!curr_reg_map.containsKey(t1) && !curr_stack_map.containsKey(t1)) 
            return _ret;
        if (curr_reg_map.containsKey(t1)) {
            t1_reg = curr_reg_map.get(t1);
        } else {
            t1_reg = "v1";
        }


        System.out.println(tab_space + "MOVE " + t1_reg + " " + exp);
        if (t1_reg == "v1") {
            if (!curr_stack_map.containsKey(t1)) System.err.println("lol");
            System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t1)) + " v1");
        }

        return _ret;
    }

    /**
        * f0 -> "PRINT"
        * f1 -> SimpleExp()
        */
    public R visit(PrintStmt n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        String exp = (String) n.f1.accept(this, argu);
        System.out.println(tab_space + "PRINT " + exp);

        return _ret;
    }

    /**
        * f0 -> Call()
        *       | HAllocate()
        *       | BinOp()
        *       | SimpleExp()
        */
    public R visit(Exp n, A argu) {
        R _ret=null;
        _ret = n.f0.accept(this, argu);
        return _ret;
    }

    /**
        * f0 -> "BEGIN"
        * f1 -> StmtList()
        * f2 -> "RETURN"
        * f3 -> SimpleExp()
        * f4 -> "END"
        */
    public R visit(StmtExp n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        String exp = (String) n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        System.out.println(tab_space + "MOVE v0 " + exp);
        return _ret;
    }

    /**
        * f0 -> "CALL"
        * f1 -> SimpleExp()
        * f2 -> "("
        * f3 -> ( Temp() )*
        * f4 -> ")"
        */
    public R visit(Call n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        String exp = (String) n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        // n.f3.accept(this, argu);
        for (int i = 0; i < 4; i++) {
            System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.size() + 8 + i) + " a" + i);
        }
        for (int i = 0; i < 10; i++) {
            System.out.println(tab_space + "ASTORE SPILLEDARG " + (curr_spilled_args + curr_stack_map.size() + 12 + i) + " t" + i);
        }

        ArrayList<Integer> args = new ArrayList<>();
        for (Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
            args.add((Integer)e.nextElement().accept(this, null));
        }
        for (int i = 0; i < Math.min(4, args.size()); i++) {
            String t_reg;
            if (curr_reg_map.containsKey(args.get(i))) {
                t_reg = curr_reg_map.get(args.get(i));
            } else {
                System.out.println(tab_space + "ALOAD v0 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(args.get(i))));
                t_reg = "v0";
            }
            System.out.println(tab_space + "MOVE a" + i + " " + t_reg);
        }
        for (int i = 4; i < args.size(); i++) {
            String t_reg;
            if (curr_reg_map.containsKey(args.get(i))) {
                t_reg = curr_reg_map.get(args.get(i));
            } else {
                System.out.println(tab_space + "ALOAD v0 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(args.get(i))));
                t_reg = "v0";
            }
            System.out.println(tab_space + "PASSARG " + (i - 3) + " " + t_reg);
        }

        System.out.println(tab_space + "CALL " + exp);

        for (int i = 0; i < 4; i++) {
            System.out.println(tab_space + "ALOAD a" + i + " SPILLEDARG " + (curr_spilled_args + curr_stack_map.size() + 8 + i));
        }
        for (int i = 0; i < 10; i++) {
            System.out.println(tab_space + "ALOAD t" + i + " SPILLEDARG " + (curr_spilled_args + curr_stack_map.size() + 12 + i));
        }

        n.f4.accept(this, argu);
        _ret = (R) "v0";
        return _ret;
    }

    /**
        * f0 -> "HALLOCATE"
        * f1 -> SimpleExp()
        */
    public R visit(HAllocate n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        String exp = (String) n.f1.accept(this, argu);
        _ret = (R) ("HALLOCATE " + exp);
        return _ret;
    }

    /**
        * f0 -> Operator()
        * f1 -> Temp()
        * f2 -> SimpleExp()
        */
    public R visit(BinOp n, A argu) {
        R _ret=null;
        String op = (String) n.f0.accept(this, argu);
        Integer t1 = (Integer) n.f1.accept(this, argu);
        String exp = (String) n.f2.accept(this, argu);
        String t1_reg;

        if (curr_reg_map.containsKey(t1)) {
            t1_reg = curr_reg_map.get(t1);
        } else {
            System.out.println(tab_space + "ALOAD v0 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t1)));
            t1_reg = "v0";
        }

        _ret = (R) (op + " " + t1_reg + " " + exp);
        return _ret;
    }

    /**
        * f0 -> "LE"
        *       | "NE"
        *       | "PLUS"
        *       | "MINUS"
        *       | "TIMES"
        *       | "DIV"
        */
    public R visit(Operator n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        _ret = (R) ((NodeToken)n.f0.choice).toString();
        return _ret;
    }

    /**
        * f0 -> Temp()
        *       | IntegerLiteral()
        *       | Label()
        */
    public R visit(SimpleExp n, A argu) {
        R _ret=null;
        _ret = n.f0.accept(this, argu);
        if (n.f0.which == 0) {
            Integer t1 = (Integer) _ret;
            if (curr_reg_map.containsKey(t1)) {
                _ret = (R) curr_reg_map.get(t1);
            } else {
                System.out.println(tab_space + "ALOAD v1 SPILLEDARG " + (curr_spilled_args + curr_stack_map.get(t1)));
                _ret = (R) "v1";
            }
        } else if (n.f0.which == 1) {
            _ret = (R) String.valueOf((Integer) _ret);
        } 
        return _ret;
    }

    /**
        * f0 -> "TEMP"
        * f1 -> IntegerLiteral()
        */
    public R visit(Temp n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        _ret = n.f1.accept(this, argu);
        return _ret;
    }

    /**
        * f0 -> <INTEGER_LITERAL>
        */
    public R visit(IntegerLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        _ret = (R) (Integer.valueOf(n.f0.toString()));
        return _ret;
    }

    /**
        * f0 -> <IDENTIFIER>
        */
    public R visit(Label n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        _ret = (R) n.f0.toString();
        return _ret;
    }

}
