//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import visitor.GJNoArguDepthFirst.func_type;

import java.text.ParseException;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
class return_value {
   String exp_temp;
   String type;
}

class variable_type {
   String name;
   String type;
}

public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public HashMap<String, HashMap<String, String>> class_vars = new HashMap<>();
   public HashMap<String, HashMap<String, func_type>> class_functions = new HashMap<>();
   public HashMap<String, String> curr_method_vars_with_types = new HashMap<>();

   public HashMap<String, HashMap<String, Integer>> class_var_map;
   public HashMap<String, HashMap<String, Integer>> class_method_map;
   public ArrayList<String> lambda_functions = new ArrayList<>();
   public HashMap<String, String> parent;
   public HashMap<String, Integer> curr_method_vars = new HashMap<>();
   String curr_class = null;
   public String no_parent;
   public String mid_name;
   int count = 0;
   String tab = "    ";
   int free_temp = 0;
   int free_label = 1;
   int free_lambda = 1;
   String return_typ = null;
   int in_lambda = 0;  
   ArrayList<String> lambda_string = new ArrayList<>();  

   public String curr_tab_space() {
      String sp = "";
      for (int i = 0; i < count; i++) {
         sp += tab;
      }
      return sp;
   }

   public ArrayList<String> get_vars(NodeListOptional n) {
      ArrayList<String> vars = new ArrayList<>();
      if (!n.present()) return vars;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         variable_type obj = (variable_type) e.nextElement().accept(this, null);
         vars.add(obj.name);
      }
      return vars;
   }

   public HashMap<String, String> get_vars_with_types(NodeListOptional n) {
      HashMap<String, String> vars= new HashMap<>();
      if (!n.present()) return vars;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         variable_type obj = (variable_type) e.nextElement().accept(this, null);
         vars.put(obj.name, obj.type);
      }
      return vars;
   }

   public String get_var_type(String id) {
      String node = curr_class;
      while (!curr_class.equals(no_parent)) {
         if (class_vars.get(node).containsKey(id)) 
            return class_vars.get(node).get(id);
         node = parent.get(node);
      }
      return null;
   }

   public int find_class_vars(String id) {
      int temp = -1;
      String node = curr_class;
      HashMap<String, Integer> var_map = class_var_map.get(curr_class);
      while (!node.equals(no_parent)) {
         if (var_map.containsKey(node + mid_name + id)) {
            temp = var_map.get(node + mid_name + id);
            break;
         }
         node = parent.get(node);
      }
      return temp;
   }

   public int get_free_temp() {
      free_temp++;
      return free_temp - 1;
   }

   public String get_free_label() {
      String res = "L" + free_label;
      free_label++;
      return res;
   }

   public String get_free_lambda() {
      String res = "Lambda" + mid_name + free_lambda;
      free_lambda++;
      return res;
   }

   public ArrayList<String> get_exp_list(NodeListOptional n) {
      ArrayList<String> vars = new ArrayList<>();
      if (!n.present()) return vars;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         vars.add((String)e.nextElement().accept(this, null));
      }
      return vars;
   }

   public int find_func(String class_type, String func_name) {
      if (is_lambda_type(class_type)) {
         return 0;
      }

      HashMap<String, Integer> func_map = class_method_map.get(class_type);
      String node = class_type;
      while (!node.equals(no_parent)) {
         if (func_map.containsKey(node + mid_name + func_name)) {
            return func_map.get(node + mid_name + func_name);
         }
         node = parent.get(node);
      }
      return -1;
   }

   public void println(String s) {
      if (in_lambda != 0) {
         String lam = lambda_string.get(lambda_string.size() - 1);
         lam += s + "\n";
         lambda_string.set(lambda_string.size() - 1, lam);
      } else {
         System.out.println(s);
      }
   }

   public void print(String s) {
      if (in_lambda != 0) {
         String lam = lambda_string.get(lambda_string.size() - 1);
         lam += s;
         lambda_string.set(lambda_string.size() - 1, lam);
      } else {
         System.out.print(s);
      }
   }

   public boolean is_lambda_type(String typ) {
      // System.out.println(typ);
      return typ.charAt(0) == '<';
   }

   public String get_argument_type_of_lambda(String typ) {
      String[] parts = typ.substring(1, typ.length() -1).split(",", 2);
      return parts[0];
   }

   public String get_return_type_of_lambda(String typ) {
      String[] parts = typ.substring(1, typ.length() -1).split(",", 2);
      return parts[1];
   }

   public String get_return_type_of_class_function(String class_type, String func_name) {
      while (!class_type.equals(no_parent)) {
         if (class_functions.get(class_type).containsKey(func_name)) {
            return class_functions.get(class_type).get(func_name).rType();
         }
         class_type = parent.get(class_type);
      }
      return "";
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      for (int i = 0; i < lambda_functions.size(); i++) {
         System.out.print(lambda_functions.get(i));
      }

      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      println("MAIN");
      count++;
      n.f14.accept(this, argu);
      count--;
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      println("END\n");
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      curr_class = (String) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      curr_class = (String) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      String type = (String) n.f0.accept(this, argu);
      String name = (String) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      variable_type obj = new variable_type();
      obj.name = name;
      obj.type = type;
      _ret = (R) obj;
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String name = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      R res = n.f4.accept(this, argu);
      ArrayList<String> vars = new ArrayList<>();
      if (res != null) vars.addAll((ArrayList<String>) res);
      int ct = vars.size();
      
      println(curr_class + mid_name + name + " [" + (ct + 1) + "]");
      println("BEGIN");
      count++;

      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);

      vars.addAll(get_vars(n.f7));
      curr_method_vars_with_types.putAll(get_vars_with_types(n.f7));
      curr_method_vars.clear();
      for (int i = 0; i < vars.size(); i++) {
         curr_method_vars.put(vars.get(i), i + 1);
      }
      free_temp = vars.size() + 1;

      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      String exp = (String) n.f10.accept(this, argu);

      println("RETURN\n" + curr_tab_space() + exp + "\nEND\n");
      count--;

      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      curr_method_vars_with_types.clear();
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      variable_type e1 = (variable_type) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ArrayList<String> ele = get_vars(n.f1);
      ele.add(0, e1.name);

      curr_method_vars_with_types.put(e1.name, e1.type);
      curr_method_vars_with_types.putAll(get_vars_with_types(n.f1));

      _ret = (R) ele;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      String type = (String) n.f0.accept(this, argu);
      String name = (String) n.f1.accept(this, argu);
      variable_type obj = new variable_type();
      obj.name = name;
      obj.type = type;
      _ret = (R) obj;
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      _ret = (R) "int[]";
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) "boolean";
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) "int";
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String id1 = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String id2 = (String) n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      _ret = (R) ("<" + id1 + "," + id2 + ">");
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      String id = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      int temp = -1;
      if (curr_method_vars.containsKey(id)) {
         temp = curr_method_vars.get(id);
         println(curr_tab_space() + "MOVE TEMP " + temp + " " + exp);
      } else {
         temp = find_class_vars(id);
         int t1 = get_free_temp();
         println(curr_tab_space() + "MOVE TEMP " + t1 + " TEMP 0");
         println(curr_tab_space() + "HSTORE TEMP " + t1 + " " + (temp * 4) + " " + exp);
      }
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String id = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp1 = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String exp2 = (String) n.f5.accept(this, argu);
      n.f6.accept(this, argu);

      int temp = - 1;
      if (curr_method_vars.containsKey(id)) {
         temp = curr_method_vars.get(id);
         int t1 = get_free_temp();
         println(curr_tab_space() + "MOVE TEMP " + t1 + " PLUS TEMP " + temp + " TIMES 4 PLUS 1 " + exp1);
         println(curr_tab_space() + "HSTORE TEMP " + t1 + " 0 " + exp2);
      } else {
         temp = find_class_vars(id);
         int t1 = get_free_temp();
         int t2 = get_free_temp();
         println(curr_tab_space() + "HLOAD TEMP " + t1 + " TEMP 0 " + (temp * 4));
         println(curr_tab_space() + "MOVE TEMP " + t2 + " PLUS TEMP " + t1 + " TIMES 4 PLUS 1 " + exp1);
         println(curr_tab_space() + "HSTORE TEMP " + t2 + " 0 " + exp2);
      }
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      String l1 = get_free_label();
      println(curr_tab_space() + "CJUMP " + exp + " " + l1);
      n.f4.accept(this, argu);
      println(l1 + " NOOP");

      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      String l1 = get_free_label();
      String l2 = get_free_label();
      println(curr_tab_space() + "CJUMP " + exp + " " + l1);
      n.f4.accept(this, argu);
      println(curr_tab_space() + "JUMP " + l2);

      println(l1 + " NOOP");
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      println(l2 + " NOOP");

      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;

      String l1 = get_free_label();
      println(l1 + " NOOP");

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      String l2 = get_free_label();
      println(curr_tab_space() + "CJUMP " + exp + " " + l2);
      n.f4.accept(this, argu);
      println(curr_tab_space() + "JUMP " + l1);
      println(l2 + " NOOP");

      return _ret;
   }

   /**
    * f0 -> "println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      println(curr_tab_space() + "PRINT " + exp);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String id = (String) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      int lamb_size = 1 + 1 + curr_method_vars.size();
      String lam1 = get_free_lambda();
      int t1 = get_free_temp();
      int t2 = get_free_temp();

      println(curr_tab_space() + "MOVE TEMP " + t1 + " HALLOCATE TIMES 4 " + lamb_size);
      println(curr_tab_space() + "MOVE TEMP " + t2 + " HALLOCATE 4");
      println(curr_tab_space() + "HSTORE TEMP " + t1 + " 0 TEMP " + t2);
      println(curr_tab_space() + "HSTORE TEMP " + t2 + " 0 " + lam1);
      println(curr_tab_space() + "HSTORE TEMP " + t1 + " 4 TEMP 0");
      for (int i = 0; i < curr_method_vars.size(); i++) {
         println(curr_tab_space() + "HSTORE TEMP " + t1 + " " + ((i + 2) * 4) + " TEMP " + (i + 1));
      }
      _ret = (R) ("TEMP " + t1);

      in_lambda++;
      int prev_tab_count = count;
      count = 1;
      int prev_temp_count = free_temp;
      free_temp = lamb_size;
     
      lambda_string.add("");
      println(lam1 + " [2]");
      println("BEGIN");
      for (int i = 0; i < curr_method_vars.size(); i++) {
         println(curr_tab_space() + "HLOAD TEMP " + (i + 2) + " TEMP 0 " + ((i + 2) * 4));
      }
      HashMap<String, Integer> prev_method_vars = new HashMap<>();
      prev_method_vars.putAll(curr_method_vars);
      curr_method_vars.clear();
      curr_method_vars.put(id, 1);
      for (Map.Entry<String, Integer> entry : prev_method_vars.entrySet()) {
         curr_method_vars.put(entry.getKey(), entry.getValue() + 1);
      }

      int t3 = get_free_temp();
      println(curr_tab_space() + "HLOAD TEMP " + t3 + " TEMP 0 4");
      println(curr_tab_space() + "MOVE TEMP 0 TEMP " + t3);

      String exp = (String) n.f4.accept(this, argu);

      println("RETURN\n" + curr_tab_space() + exp + "\nEND\n");
      curr_method_vars = prev_method_vars;
      free_temp = prev_temp_count;
      count = prev_tab_count;
      in_lambda--;
      lambda_functions.add(lambda_string.getLast());
      lambda_string.removeLast();
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " NE PLUS " + exp1 + " " + exp2 + " 2");
      println(curr_tab_space() + "MOVE TEMP " + t1 + " NE 1 TEMP " + t1);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " NE PLUS " + exp1 + " " + exp2 + " 0");
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " LE " + exp1 + " " + exp2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " NE " + exp1 + " " + exp2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " PLUS " + exp1 + " " + exp2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " MINUS " + exp1 + " " + exp2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " TIMES " + exp1 + " " + exp2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " DIV " + exp1 + " " + exp2);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String exp1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp2 = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      int t1 = get_free_temp();
      int t2 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t2 + " PLUS " + exp1 + " TIMES 4 PLUS 1 " + exp2);
      println(curr_tab_space() + "HLOAD TEMP " + t1 + " TEMP " + t2 + " 0");
      _ret = (R) ("TEMP " + t1);
      return _ret; 
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String exp = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      int t1 = get_free_temp();
      println(curr_tab_space() + "HLOAD TEMP " + t1 + " " + exp + " 0");
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      String e1 = (String) n.f0.accept(this, argu);
      String class_type = return_typ;

      n.f1.accept(this, argu);
      String func = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      
      R ret = n.f4.accept(this, argu);
      ArrayList<String> vars = new ArrayList<>();
      vars.add(e1);
      if (ret != null) vars.addAll((ArrayList<String>) ret);
      n.f5.accept(this, argu);

      int temp = find_func(class_type, func);
      int t1 = get_free_temp();
      int t2 = get_free_temp();
      int t3 = get_free_temp();
      println(curr_tab_space() + "HLOAD TEMP " + t1 + " " + e1 + " 0");
      println(curr_tab_space() + "HLOAD TEMP " + t2 + " TEMP " + t1 + " " + (temp * 4));
      println(curr_tab_space() + "MOVE TEMP " + t3 + " CALL TEMP " + t2);
      print(curr_tab_space() + "(");
      for (int i = 0; i < vars.size(); i++) {
         if (i != vars.size() - 1) print(vars.get(i) + " ");
         else println(vars.get(i) + ")");
      }
      _ret = (R) ("TEMP " + t3);
      if (!is_lambda_type(class_type)) return_typ = get_return_type_of_class_function(class_type, func);
      else return_typ = get_return_type_of_lambda(class_type);
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      String exp = (String) n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      ArrayList<String> vars = new ArrayList<>();
      vars.add(exp);
      vars.addAll(get_exp_list(n.f1));
      _ret = (R) vars;
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      if (n.f0.which == 3) {
         int temp = -1;
         String id = (String) _ret;
         if (curr_method_vars.containsKey(id)) {
            temp = curr_method_vars.get(id);
            _ret = (R) ("TEMP " + temp);
            return_typ = curr_method_vars_with_types.get(id);
         } else {
            temp = find_class_vars(id);
            int t1 = get_free_temp();
            println(curr_tab_space() + "HLOAD TEMP " + t1 + " TEMP 0 " + (temp * 4));
            _ret = (R) ("TEMP " + t1);
            return_typ = get_var_type(id);
         }
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String val = n.f0.toString();
      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " " + val);
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " 1");
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " 0");
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) "TEMP 0";
      return_typ = curr_class;
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String exp = (String) n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      int t1 = get_free_temp();
      int t2 = get_free_temp();
      int t3 = get_free_temp();
      String l1 = get_free_label();
      String l2 = get_free_label();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " HALLOCATE TIMES 4 PLUS 1 " + exp);
      println(curr_tab_space() + "HSTORE TEMP " + t1 + " 0 " + exp);
      println(curr_tab_space() + "MOVE TEMP " + t2 + " 1");
      println(l1 + " NOOP");
      println(curr_tab_space() + "CJUMP NE TEMP " + t2 + " PLUS 1 " + exp + " " + l2);
      println(curr_tab_space() + "MOVE TEMP " + t3 + " PLUS TEMP " + t1 + " TIMES 4 TEMP " + t2);
      println(curr_tab_space() + "HSTORE TEMP " + t3 + " 0 0");
      println(curr_tab_space() + "MOVE TEMP " + t2 + " PLUS 1 TEMP " + t2);
      println(curr_tab_space() + "JUMP " + l1);
      println(l2 + " NOOP");
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String type = (String) n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      int class_size = class_var_map.get(type).size() + 1;
      class_size *= 4;
      int class_methods = class_method_map.get(type).size();
      class_methods *= 4;
      HashMap<Integer,String> int_to_func_map = new HashMap<>();
      for (Map.Entry<String, Integer> entry : class_method_map.get(type).entrySet()) {
         int_to_func_map.put(entry.getValue(), entry.getKey());
      }

      int t1 = get_free_temp();
      int t2 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " HALLOCATE " + class_size);
      println(curr_tab_space() + "MOVE TEMP " + t2 + " HALLOCATE " + class_methods);
      println(curr_tab_space() + "HSTORE TEMP " + t1 + " 0 TEMP " + t2);
      for (int i = 0; i < class_methods/4; i++) {
         println(curr_tab_space() + "HSTORE TEMP " + t2 + " " + (i * 4) + " " + int_to_func_map.get(i));
      }
      for (int i = 1; i < class_size/4; i++) {
         println(curr_tab_space() + "HSTORE TEMP " + t1 + " " + (i * 4) + " 0");
      }
      
      return_typ = type;
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String exp = (String) n.f1.accept(this, argu);
      int t1 = get_free_temp();
      println(curr_tab_space() + "MOVE TEMP " + t1 + " NE " + exp + " 1");
      _ret = (R) ("TEMP " + t1);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

}
