//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   String tab_space = "    ";
   Integer curr_spilled_args;
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Integer t1 = (Integer) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      Integer t2 = (Integer) n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      Integer t3 = (Integer) n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      System.out.println(tab_space + ".text");
      System.out.println(tab_space + ".globl main");
      System.out.println("main:");
      System.out.println(tab_space + "sw $fp, -4($sp)");
      System.out.println(tab_space + "sw $ra, -8($sp)");
      System.out.println(tab_space + "move $fp, $sp");
      System.out.println(tab_space + "subu $sp, $sp, " + (t2 * 4 + 16));
      curr_spilled_args = t2 * 4;
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      System.out.println(tab_space + "lw $ra, -8($fp)");
      System.out.println(tab_space + "move $sp, $fp");
      System.out.println(tab_space + "lw $fp, -4($fp)");
      System.out.println(tab_space + "jr $ra");
      System.out.println();

      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      System.out.println(tab_space + ".data");
      System.out.println(tab_space + ".align 0");
      System.out.println("newl:    .asciiz \"\\n\"");

      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      // n.f0.accept(this, argu);
      for (Enumeration<Node> e1 = n.f0.elements(); e1.hasMoreElements();) {
         for (Enumeration<Node> e2 = ((NodeSequence)e1.nextElement()).elements(); e2.hasMoreElements();) {
            R res = e2.nextElement().accept(this, null);
            if (res != null) {
               System.out.println((String)res + ":");
            }
         }
      }
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      String l1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Integer t1 = (Integer) n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      Integer t2 = (Integer) n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      Integer t3 = (Integer) n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      System.out.println(tab_space + ".text");
      System.out.println(tab_space + ".globl " + l1);
      System.out.println(l1 + ":");
      System.out.println();
      System.out.println(tab_space + "sw $fp, -4($sp)");
      System.out.println(tab_space + "sw $ra, -8($sp)");
      System.out.println(tab_space + "move $fp, $sp");
      System.out.println(tab_space + "subu $sp, $sp, " + (t2 * 4 + 16));
      curr_spilled_args = t2 * 4;

      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      System.out.println(tab_space + "lw $ra, -8($fp)");
      System.out.println(tab_space + "move $sp, $fp");
      System.out.println(tab_space + "lw $fp, -4($fp)");
      System.out.println(tab_space + "jr $ra");
      System.out.println();

      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg = (String) n.f1.accept(this, argu);
      String l1 = (String) n.f2.accept(this, argu);
      System.out.println(tab_space + "beqz $" + reg + " " + l1);

      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String l1 = (String) n.f1.accept(this, argu);
      System.out.println(tab_space + "j " + l1);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String) n.f1.accept(this, argu);
      Integer v1 = (Integer) n.f2.accept(this, argu);
      String r2 = (String) n.f3.accept(this, argu);
      System.out.println(tab_space + "sw $" + r2 + ", " + v1 + "($" + r1 + ")");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String) n.f1.accept(this, argu);
      String r2 = (String) n.f2.accept(this, argu);
      Integer v1 = (Integer) n.f3.accept(this, argu);
      System.out.println(tab_space + "lw $" + r1 + ", " + v1 + "($" + r2 + ")");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String) n.f1.accept(this, argu);
      R res = n.f2.accept(this, (A)r1);
      if (n.f2.f0.which == 2) {
         switch (((SimpleExp)n.f2.f0.choice).f0.which) {
            case 0:
               System.out.println(tab_space + "move $"+ r1 + ", $" + (String)res);
               break;
            case 1:
               System.out.println(tab_space + "li $" + r1 + ", " + (Integer)res);
               break;
            case 2:
               System.out.println(tab_space + "la $" + r1 + ", " + (String)res);
               break;
            default:
               break;
         }
      }
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R res = n.f1.accept(this, argu);
      System.out.println(tab_space + "sw $a0, -12($fp)");
      System.out.println(tab_space + "sw $v0, -16($fp)");
      if (n.f1.f0.which == 0) 
         System.out.println(tab_space + "add $a0, $0, $" + (String)res);
      else 
         System.out.println(tab_space + "li $a0, " + (Integer)res);
      
      System.out.println(tab_space + "addi $v0, $0, 1");
      System.out.println(tab_space + "syscall");

      System.out.println(tab_space + "la $a0, newl");
      System.out.println(tab_space + "li $v0, 4");
      System.out.println(tab_space + "syscall");

      System.out.println(tab_space + "lw $a0, -12($fp)");
      System.out.println(tab_space + "lw $v0, -16($fp)");
      
      return _ret;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public R visit(ALoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String) n.f1.accept(this, argu);
      Integer v1 = (Integer) n.f2.accept(this, argu);
      System.out.println(tab_space + "lw $" + r1 + ", " + (curr_spilled_args - (v1 * 4) - 4) + "($sp)");

      return _ret;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public R visit(AStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer v1 = (Integer) n.f1.accept(this, argu);
      String r1 = (String) n.f2.accept(this, argu);
      System.out.println(tab_space + "sw $" + r1 + ", " + (curr_spilled_args - (v1 * 4) - 4) + "($sp)");

      return _ret;
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public R visit(PassArgStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer v1 = (Integer) n.f1.accept(this, argu);
      String r1 = (String) n.f2.accept(this, argu);
      System.out.println(tab_space + "sw $" + r1 + ", -" + (16 + v1 * 4) + "($sp)");

      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public R visit(CallStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R res = n.f1.accept(this, argu);
      if (n.f1.f0.which == 0) {
         System.out.println(tab_space + "jalr $" + (String)res);
      } else {
         System.out.println(tab_space + "jal " + (String)res);
      }
   
      return _ret;
   }

   /**
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R res = n.f1.accept(this, argu);
      System.out.println(tab_space + "sw $a0, -12($fp)");
      System.out.println(tab_space + "sw $v0, -16($fp)");
      if (n.f1.f0.which == 0) {
         System.out.println(tab_space + "add $a0, $0, $" + (String)res);
      } else {
         System.out.println(tab_space + "addi $a0, $0, " + (Integer)res);
      }
      System.out.println(tab_space + "addi $v0, $0, 9");
      System.out.println(tab_space + "syscall");
      String inp = (String) argu;
      System.out.println(tab_space + "move $" + inp + ", $v0");
      if (!inp.equals("a0")) System.out.println(tab_space + "lw $a0, -12($fp)");
      if (!inp.equals("v0")) System.out.println(tab_space + "lw $v0, -16($fp)");

      return _ret; 
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String) n.f0.accept(this, argu);
      String r1 = (String) n.f1.accept(this, argu);
      R res = n.f2.accept(this, argu);
      String inp = (String) argu;
      String r2;
      if (n.f2.f0.which == 0) {
         r2 = (String) res;
      } else {
         if (r1.equals("v0")) {
            System.out.println(tab_space + "sw $v1, -16($fp)");
            System.out.println(tab_space + "li $v1, " + (Integer)res);
            r2 = "v1";
         } else {
            System.out.println(tab_space + "sw $v0, -16($fp)");
            System.out.println(tab_space + "li $v0, " + (Integer)res);
            r2 = "v0";
         }
      }

      switch (op) {
         case "LE":
            System.out.println(tab_space + "sle $" + inp + ", $" + r1 + ", $" + r2);
            break;
         case "NE":
            System.out.println(tab_space + "sne $" + inp + ", $" + r1 + ", $" + r2);
            break;
         case "PLUS":
            System.out.println(tab_space + "add $" + inp + ", $" + r1 + ", $" + r2);
            break;
         case "MINUS":
            System.out.println(tab_space + "sub $" + inp + ", $" + r1 + ", $" + r2);
            break;
         case "TIMES":
            System.out.println(tab_space + "mult $" + r1 + ", $" + r2);
            System.out.println(tab_space + "mflo $" + inp);
            break;
         case "DIV":
            System.out.println(tab_space + "div $" + inp + ", $" + r1 + ", $" + r2);
            break;
         default:
            break;
      }

      if (n.f2.f0.which == 1 && !inp.equals(r2)) {
         System.out.println(tab_space + "lw $" + r2 + ", -16($fp)");
      }

      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)(((NodeToken)n.f0.choice).toString());
      return _ret;
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public R visit(SpilledArg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    */
   public R visit(Reg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)((NodeToken)n.f0.choice).toString();
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) (Integer.valueOf(n.f0.toString()));
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public R visit(SpillInfo n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <SPILLED>
    *       | <NOTSPILLED>
    */
   public R visit(SpillStatus n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

}
